name: Calculator 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: mdnurhaziq/testrepo
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      
      - name: Install dependencies
        run: |
          pip install pytest pytest-mock

      - name: Run pytest
        run: pytest test_calculator.py
